export const DAY_MS = 86_400_000;
export const ETH40_SPEC = Object.freeze({
  version: "eth40-forward-v1" as const,
  candidateId: "sma_eth-040",
  liveTradingEnabled: false,
  automaticPromotionAllowed: false,
  historicalScreenPassed: false,
  validatedProfitable: false,
  initialCashUsd: 10_000,
  warmupBars: 90,
  movingAverageDays: 40,
  entryBandFraction: ((1 + .008) * (1 + .0003) / ((1 - .008) * (1 - .0003))) - 1,
  finalizationDelayMs: 60_000,
  signalToExecutionDays: 2,
  executionWindowMs: 60_000,
  maximumQuoteAgeMs: 5_000,
  maximumExchangeClockLeadMs: 1_000,
  maximumRulesAgeMs: DAY_MS,
  entryFeeBps: 80,
  exitFeeBps: 80,
  maximumEntryUsd: 1_000,
  maximumEntryEquityFraction: .1,
  completedDayVolumeParticipation: .001,
  displayedDepthParticipation: .05,
  bookPriceCollarBps: 10,
  minimumCompletedEpisodes: 10,
  reviewCalendarMonths: 6,
  feeSource: "https://www.kraken.com/features/fee-schedule",
  feeVerifiedDate: "2026-09-10",
  feeAssumption: "Public entry-tier spot taker fee; no private account fee tier assumed.",
  executionContract: "Signal candle i trades in the first 60 seconds of UTC day i+2 using a fresh checksum-verified book. Missed windows are recorded, never backfilled. At most one fill per account per day; partial residual exits wait for a subsequent eligible daily cash signal. No additions to open positions.",
  forwardDifference: "Daily signal and sizing are frozen. Executable book walking, 5% displayed-depth participation and missed fills replace historical OHLC prices plus 3bp assumed slippage. These are prospective paper execution assumptions, not guaranteed exchange fills.",
  launchContract: "Start with cash. The launch UTC candle is the first prospective signal candle; the first execution opportunity is its day i+2. Passive ETH/BTC each buy once with the same $1,000/10% cap, retain remaining cash, and never rebalance.",
});
