import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const out = 'reports/spot-order-dashboard-2026-09-10';
const run = (args) => execFileSync('docker', args, { encoding: 'utf8' }).trim();
const closureCode = `const {readRiskTrainingSourceHashes}=await import('./dist/src/distribution/risk-training-source.js'); const {createHash}=await import('node:crypto'); const hashes=readRiskTrainingSourceHashes(); console.log(JSON.stringify({count:hashes.length,sha256:createHash('sha256').update(JSON.stringify(hashes)).digest('hex'),hashes}));`;
const base = 'sha256:4e5d6e8ecd4e816fdcb550caa11c20ff9172d0aa580ed99deaf4bccf8bca0c1a';
const before = JSON.parse(run(['run','--rm','--network','none',base,'node','--input-type=module','-e',closureCode]));
const after = JSON.parse(run(['run','--rm','--network','none','crypto-trade-engine:spot-dashboard-v1','node','--input-type=module','-e',closureCode]));
assert.deepEqual(after, before);
assert.equal(before.count,82);
assert.equal(before.sha256,'c57475ab04ce281cbd83f86f95f0099d56d24ef5edcee758e293be197f8d036b');
const copyRoot = '/tmp/spot-order-migration-image-check';
mkdirSync(copyRoot);
run(['cp','crypto-spot-trend-paper:/app/data/.',copyRoot]);
const migrateCode = `
 const assert=(await import('node:assert/strict')).default;
 const {readFile}=await import('node:fs/promises');
 const {createHash}=await import('node:crypto');
 const {loadSpotPaperEvidence}=await import('./dist/src/spot-trend/evidence.js');
 const {loadSpotPaperEnvelope,migrateSpotPaperEnvelope}=await import('./dist/src/spot-trend/paper-main.js');
 const evidence=await loadSpotPaperEvidence('reports/new-spot-system-2026-09-10/historical-study','reports/new-spot-system-2026-09-10/audit.json');
 assert.equal(evidence.evidenceSha256,'3eed46dd2a5f17dc48e87e190243971754b1c7b0394ebcadb4eb289d30ebb509');
 const files=['paper.ts','paper-main.ts','market.ts','evidence.ts','journal.ts','orders.ts','migration.ts'].map(f=>'src/spot-trend/'+f);
 const hash=b=>createHash('sha256').update(b).digest('hex');
 const sourceSha=hash(JSON.stringify(await Promise.all(files.map(async file=>({file,sha256:hash(await readFile(file))})))));
 const before=await loadSpotPaperEnvelope('/check/state.json','/check');
 const after=await migrateSpotPaperEnvelope(before,'/check',sourceSha);
 assert.deepEqual(after.state.account,before.state.account);
 assert.equal(after.state.startedAtMs,before.state.startedAtMs);
 assert.equal(after.state.cycles,before.state.cycles);
 assert.deepEqual(await loadSpotPaperEnvelope('/check/state.json','/check'),after);
 console.log(JSON.stringify({passed:true,evidenceSha256:evidence.evidenceSha256,runtimeSha256:sourceSha,version:after.state.version,account:after.state.account,cycles:after.state.cycles,migrationEvidence:after.migrationEvidence}));
`;
const spot = JSON.parse(run(['run','--rm','--network','none','-v',copyRoot+':/check','crypto-spot-trend-paper:v2','node','--input-type=module','-e',migrateCode]));
const images = JSON.parse(run(['image','inspect','crypto-trade-engine:spot-dashboard-v1','crypto-spot-trend-paper:v2'])).map(x=>({id:x.Id,tags:x.RepoTags}));
const report={passed:true,network:'none',futuresSourceClosure:after,spotCopiedJournalMigration:spot,images};
writeFileSync(out+'/image-verification.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({passed:true,futuresSourceFiles:after.count,futuresSourceSha256:after.sha256,spot,images},null,2));
