import { execFileSync } from 'node:child_process';
import { cpSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const out=resolve('reports/spot-continuous-entries-2026-09-10');
const run=args=>execFileSync('docker',args,{encoding:'utf8',maxBuffer:16*1024*1024}).trim();
const images=JSON.parse(run(['image','inspect','crypto-trade-engine:spot-dashboard-v3','crypto-trade-engine:spot-dashboard-v4','crypto-spot-trend-paper:v3']));
assert.deepEqual(images[0].Config,images[1].Config);
assert.deepEqual(images[0].RootFS.Layers.slice(0,-1),images[1].RootFS.Layers.slice(0,-1));
const closureCode=`const {readRiskTrainingSourceHashes}=await import('./dist/src/distribution/risk-training-source.js');const {createHash}=await import('node:crypto');const hashes=readRiskTrainingSourceHashes();console.log(JSON.stringify({count:hashes.length,sha256:createHash('sha256').update(JSON.stringify(hashes)).digest('hex')}));`;
const closure=JSON.parse(run(['run','--rm','--network','none',images[1].Id,'node','--input-type=module','-e',closureCode]));
assert.equal(closure.count,82);assert.equal(closure.sha256,'c57475ab04ce281cbd83f86f95f0099d56d24ef5edcee758e293be197f8d036b');
const spotCheck=JSON.parse(readFileSync(out+'/spot-image-verification.json'));
assert.equal(spotCheck.passed,true);assert.equal(spotCheck.imageId,images[2].Id);
const {migration,smoke}=spotCheck;
const safeImages=images.map(x=>({id:x.Id,tags:x.RepoTags,layers:x.RootFS.Layers}));
const result={passed:true,network:'none',futuresConfigurationAndPreviousLayersUnchanged:true,closure,migration,smoke,images:safeImages};
writeFileSync(out+'/image-verification.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({passed:true,closure,migration,smokeChecks:smoke.checks.length,images:safeImages.map(({id,tags})=>({id,tags}))},null,2));
