/** One reserved-window test. No parameter changes or follow-on search permitted. */
export const CHANNEL_HOLDOUT_SPEC = Object.freeze({
  version: "channel-v2-one-reserved-2026-validation-v1",
  strategyVersion: "btc-eth-daily-55-20-channel-price-protected-v2",
  startMs: Date.UTC(2026, 0, 1), endMs: Date.UTC(2026, 7, 1), warmupStartMs: Date.UTC(2025, 8, 1),
  minimumCompleteWarmupDays: 100,
  warmup: "122_CALENDAR_DAYS_FROM_2025_09_01;NO_POSITIONS_OR_PNL_IN_WARMUP;AT_LEAST_100_COMPLETE_CONSECUTIVE_DAYS_BEFORE_TEST",
  scenarios: ["base", "stress"] as const, minimumBaseClosedEpisodes: 6,
  bootstrap: { repetitions: 2000, contiguousBlockWeeks: 4, lowerQuantile: .05, seed: 0x3d729a41,
    metric: "MEAN_COMPLETE_MONDAY_UTC_WEEKLY_MARKED_NET_CHANGE_ON_HOLDOUT_ALONE" },
  requirements: ["KNOWN_FUNDED_ACCOUNTING_NO_HELD_MISSING_DATA_OR_UNRESOLVED_POSITIONS",
    "STRICTLY_POSITIVE_NET_IN_BASE_AND_STRESS", "AT_LEAST_SIX_BASE_CLOSED_EPISODES",
    "HOLDOUT_ALONE_FOUR_WEEK_BOOTSTRAP_LOWER_FIVE_PERCENT_MEAN_WEEKLY_NET_STRICTLY_POSITIVE",
    "NO_SESSION_0_75_PERCENT_ROLLING_0_75_PERCENT_OR_ACCOUNT_DRAWDOWN_5_PERCENT_BREACH"],
  previouslyKnownMissingFundingSourceStartsUtc: ["2026-02-04T12:00:00.000Z", "2026-02-13T18:00:00.000Z", "2026-05-09T06:00:00.000Z"],
  missingFundingPolicy: "KEEP_ABSENT;NO_ZERO_FILL_NO_ANALYTICS_SUBSTITUTION;HELD_EXPOSURE_INVALIDATES_FUNDED_RESULT",
  fundingMerge: "OFFICIAL_ARCHIVED_NORMALIZED_RATES_PLUS_HASH_VERIFIED_OFFICIAL_HISTORICAL_RATE_API;IDENTICAL_OVERLAPS_ONLY;SOURCE_TIMESTAMP_PLUS_ONE_HOUR",
  originalDevelopmentBootstrapFailurePreserved: true,
  originalPlannerHistoricalGateUnchanged: true,
  benchmarks: "CASH_ZERO_AND_SEPARATE_COSTED_CONSTANT_UNIT_BTC_ETH_LONGS_DESCRIPTIVE_ONLY",
  pilotAdditionalRequirements: ["INDEPENDENT_CASH_ORDER_FEE_AND_FUNDING_RECONCILIATION",
    "CURRENT_ACCOUNT_FEES_AND_VENUE_RULES_VERIFIED", "RECORDED_CURRENT_QUOTE_EXECUTION_EVIDENCE",
    "SEPARATELY_REVIEWED_PAPER_ONLY_QUALIFICATION_AND_INSTALLED_ROUTE"],
  afterResults: "NO_PARAMETER_OR_GATE_CHANGES_NO_FURTHER_VARIANTS;PRESERVE_ALL_FAILURES",
  rootReviewRequiredBeforeEvaluation: true, realOrdersAllowed: false, futureProfitGuaranteed: false,
});
